### ISSUE TITLE
additional models?

### ISSUE THREAD

**Issue by Selur** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#13]
https://github.com/nihui/rife-ncnn-vulkan supports:
- rife-HD
- rife-UHD
- rife-anime
- rife-v2.3
- rife-v2.4
- rife-v2
- rife-v3.0
- rife-v3.1
- rife-v4
- rife 

woud be nice if all those could be supported. :)

**Comment by styler00dollar** [comment]
[This fork](https://github.com/DaGooseYT/VapourSynth-RIFE-ncnn-Vulkan/tree/master/models) added `rife-v2` and `rife-v3.0`. Technically missing models would be:
- rife-HD
- rife-UHD
- rife-v2.3
- rife
- rife-v4

In my personal opinion, `rife-v4` should be added first since the other models are a bit outdated.

**Comment by styler00dollar** [comment]
In case you are interested, I updated the python ncnn rife API to have all current nihui models in [styler00dollar/rife-ncnn-vulkan-python](https://github.com/styler00dollar/rife-ncnn-vulkan-python) and added them to be in VapourSynth [here](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/main/src/rife.py).
